### PR TITLE
added plugin "pageurl"

### PR DESCRIPTION
**Pull request by raffaelj**
The addon "pageurl" has no effect right now, but it will if
agentejo/cockpit#1044 will get merged.

The addon "assetpath" doesn't exist right now. It is part of
"mediapath". I changed that in the PR above, too.

### CODE REVIEW

**Comment by pauloamgomes** [comment]
Hey @raffaelj , that seems already merged, can confirm the change?

**Comment by raffaelj** [comment]
The plugins are now called "cpmediapath", "cpassetpath" and "cpcollectionlink". So this PR is outdated and after changing the names in your addon, it wouldn't be backwards compatible.

see: https://github.com/agentejo/cockpit/commit/6e8bee2ebc5d6281a939ba9402f1c2b6668da505

**Comment by pauloamgomes** [comment]
Ok, can you update it?

**Comment by raffaelj** [comment]
I updated it

**Comment by pauloamgomes** [comment]
thanks!

**Pull request merged**
